version: "3.8"

services:
  localhost:
    image: alpine:latest
    command: sleep infinity
    ports:
      - "8079:8079"

  keycloak-ocs-compose:
    image: quay.io/keycloak/keycloak:24.0.3
    network_mode: "service:localhost"
    command: -v start-dev --import-realm
    environment:
      KC_HTTP_PORT: 8079
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./:/opt/keycloak/data/import
      - ./keycloak/import/:/opt/keycloak/data/import/
    restart: on-failure

