server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clothesdb?createDatabaseIfNotExist=true
    username: root
    password: sqlPass
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    hibernate:
      hbm2ddl:
        auto:
  jpa:
    # database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update # ###### update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect